# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
        
# --------------------------------------
# Debugging
# --------------------------------------
#     - name: Debugging with ssh
#      # You may pin to the exact commit or the version.
#       uses: lhotari/action-upterm@v1
# --------------------------------------

name: BedyBotDB Test Coverage

on:
  # Manual action
  workflow_dispatch:
  
  pull_request:
    branches:
    - feature/treeRefactor
    
  release:
    types: [created, edited]
    branches:
    - feature/treeRefactor 
  
env:
     NODE_ENV:  "test"
     DB_NAME:  "bedyapi-dbtest"
     DB_USER:  "root"
     DB_PASSWORD:  ${{ secrets.DB_PASSWD }}
     DB_HOST: localhost
     DB_PORT: 3306

permissions:
   pull-requests: write
   packages: write
    # deployments
    
jobs:
  build:
    runs-on: ubuntu-latest
    environment: BedyBotDB-TestEnv

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
  
    - name: Create test config file
      uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "src/config/config.js"
        FILE_DATA: ${{ secrets.CONFIG_CONTENT }} 
        
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary,

    # https://github.com/marketplace/actions/start-mariadb
    - name: Start MariaDB
      uses: getong/mariadb-action@v1.1
      with:
        host port: 3306 # Optional, default value is 3306. The port of host
        container port: 3306 # Optional, default value is 3306. The port of container
        character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        # mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
        mysql database: "bedyapi-dbtest" # Optional, default value is "test". The specified database which will be create
        mysql root password: ${{ secrets.DB_PASSWD }} # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'developer' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: ${{ secrets.DB_PASSWD }} # Required if "mysql user" exists. The password for the "mysql user"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci

    - name: Debugging with ssh
      uses: lhotari/action-upterm@v1

# ---------------------------------------
# On Pull request
# - Add comment test coverage in PR
# ---------------------------------------
    - name: Run Test Coverage
      if: ${{ github.event_name == 'pull_request' }}
      run: npm run test:git_json 

    # https://github.com/marketplace/actions/report-nyc-coverage
    - name: Report NYC coverage
      if: ${{ github.event_name == 'pull_request' }}
      uses: sidx1024/report-nyc-coverage-github-action@v1.2.7
      with:
        # Path to coverage file generated by "nyc report".
        coverage_file: "coverageJson/coverage-summary.json"
        comment_template_file: "template/comment-template.md"

# ---------------------------------------
# On Manual deploy
# -Commit coverage result on SSH
# ---------------------------------------
    - name: Run Test Coverage
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: npm run test:git_html
      
    - name: Upload coverage artifact
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/upload-artifact@v3.1.2
      with:
          name: test-coverage-result
          path: "coverageHtml/**"
          retention-days: 1

    - name: Download coverage artifact
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: actions/download-artifact@v2.1.1
      with:
          name: test-coverage-result
          path: BedyBotDB     
      
    - name: Publish on SSH
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        passphrase: ${{ secrets.PASSPHRASE }}
        key: ${{ secrets.KEY }}
        source: BedyBotDB/*
       # source: "coverage/*.*"
        target: '/home/bedybot-docker/shared/coverage/www/'
        
    - name: Upload coverage reports to Codecov
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: BedyBotDB/*
